### ISSUE TITLE
question about "You will not be able to log into EAS using your LDAP credentials by default."

### ISSUE THREAD

**Issue by theoneandonly-vector** [Programmierus/ldap-mailcow#16]
"You will not be able to log into mailcow UI or EAS using your LDAP credentials by default."

why does this affect AES when we can login -> SoGo web?

**Comment by Programmierus** [comment]
sorry, but i didn't get your question

**Comment by theoneandonly-vector** [comment]
1. AES stands for Exchange Active Sync I would think.
2. Exchange Active Sync is handled by SoGo.
3. SoGo-web works without the workaround

so why do I need to use the workaround to get "Exchange Active Sync" working?

**Comment by Programmierus** [comment]
AES stands for Advanced Encryption Standard. AES != EAS.

SOGo works just because it's basically an IMAP client, authentication goes through dovecot which is being configured by my script.

EAS, in particular auto-configuration, works directly with mailcow user/pass-db, which, without a workaround, knows nothing about LDAP authentication.

**Comment by theoneandonly-vector** [comment]
I see, thx :)
